language: ruby
addons:
  apt:
    sources:
      - elasticsearch-6.x
    packages:
      - elasticsearch
services:
  - elasticsearch
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
sudo: false
cache: bundler
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
