language: ruby
rvm:
  - 2.5
  - 2.6
sudo: true
services:
  - elasticsearch
cache: bundler
before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.8.4.deb && sudo service elasticsearch restart
  - bundle exec rake test_app
  - sleep 20
script:
  - bundle exec rspec spec
